name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lints:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: cargo fmt
      - name: Clippy
        run: cargo clippy -- -D warnings

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Cache
        uses: Swatinem/rust-cache@v1
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
